// Copyright 2020 Emelkhovsky Ekaterina
#ifndef MODULES_TASK_1_EMELKHOVSKY_K_INTEGRATION_MONTE_CARLO_INTEGRATION_MONTE_CARLO_H_
#define MODULES_TASK_1_EMELKHOVSKY_K_INTEGRATION_MONTE_CARLO_INTEGRATION_MONTE_CARLO_H_

int funcF(int x);
double ParallelFunc(int N, int a, int b);
double EasyFunc(int N, int a, int b);

#endif  // MODULES_TASK_1_EMELKHOVSKY_K_INTEGRATION_MONTE_CARLO_INTEGRATION_MONTE_CARLO_H_
