// Copyright 2020 Bessolitsyn Sergay
#ifndef MODULES_TASK_2_BESSOLITSYN_S_DINING_PHILOSOPHERS_DINING_PHILOSOPHERS_H_
#define MODULES_TASK_2_BESSOLITSYN_S_DINING_PHILOSOPHERS_DINING_PHILOSOPHERS_H_

#include <vector>

int waiter(int iterations);

void philosopher(int plates_for_eating);

#endif  // MODULES_TASK_2_BESSOLITSYN_S_DINING_PHILOSOPHERS_DINING_PHILOSOPHERS_H_
